services:
  _defaults:
    public: true
    autowire: true

  HeimrichHannot\IsotopeSubscriptionsBundle\Manager\:
    resource: '../../Manager/*'

  HeimrichHannot\IsotopeSubscriptionsBundle\Controller\:
    resource: '../../Controller/*'

  HeimrichHannot\IsotopeSubscriptionsBundle\DataContainer\:
    resource: '../../DataContainer/*'
