services:
  huh.isotope_subscriptions.manager.subscriptions:
    class: HeimrichHannot\IsotopeSubscriptionsBundle\Manager\IsotopeSubscriptions
    public: true
    arguments:
      - "@contao.framework"