services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\IsotopeSubscriptionsBundle\:
    resource: '../../{Controller,DataContainer,Manager}/*'

  HeimrichHannot\IsotopeSubscriptionsBundle\Manager\:
    resource: '../../Manager/*'
    public: true
