services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  HeimrichHannot\IsotopeSubscriptionsBundle\:
    resource: '../../{Controller,DataContainer,EventListener,Manager}/*'
