services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  HeimrichHannot\IsotopeSubscriptionsBundle\:
    resource: '../../{Controller,DataContainer,Manager}/*'
    autoconfigure: true
    public: true
